name: hangman_game
description: "Hangman game with flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  go_router: ^14.6.0
  injectable: ^2.5.0
  intl: ^0.20.1
  supabase: ^2.6.0
  supabase_flutter: ^2.8.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  fonts:
    - family: BubblegumSans
      fonts:
        - asset: assets/fonts/bubblegum_sans/BubblegumSans-Regular.ttf
          weight: 400
